name: autobook
description: Vehicle maintenances management app.

publish_to: 'none'

version: 1.1.1+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  intl: ^0.17.0
  flutter_spinkit: "^5.0.0"
  amplify_flutter: ^0.2.2
  amplify_core: ^0.2.2
  amplify_auth_cognito: ^0.2.2
  amplify_api: ^0.2.2
  flutter_launcher_icons: "^0.9.1"

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"